class SyllabicConvertor:
    syllables = [
        ("ᑈ", "pwaa"),
        ("ᑥ", "twaa"),
        ("ᒂ", "kwaa"),
        ("ᒠ", "chwaa"),
        ("ᒺ", "mwaa"),
        ("ᓏ", "nwaa"),
        ("ᔄ", "swaa"),
        ("ᔽ", "ywaa"),
        ("ᐎ", "wii"),
        ("ᐛ", "waa"),
        ("ᐱ", "pii"),
        ("ᐳ", "puu"),
        ("ᐸ", "paa"),
        ("ᑎ", "tii"),
        ("ᑐ", "tuu"),
        ("ᑕ", "taa"),
        ("ᑭ", "kii"),
        ("ᑯ", "kuu"),
        ("ᑲ", "kaa"),
        ("ᒋ", "chii"),
        ("ᒍ", "chuu"),
        ("ᒐ", "chaa"),
        ("ᒥ", "mii"),
        ("ᒧ", "muu"),
        ("ᒪ", "maa"),
        ("ᓂ", "nii"),
        ("ᓄ", "nuu"),
        ("ᓇ", "naa"),
        ("ᓯ", "sii"),
        ("ᓱ", "suu"),
        ("ᓴ", "saa"),
        ("ᔨ", "yii"),
        ("ᔪ", "yuu"),
        ("ᔭ", "yaa"),
        ("ᐃ", "ii"),
        ("ᐅ", "uu"),
        ("ᐊ", "aa"),
        ("ᑈ", "pwa"),
        ("ᑥ", "twa"),
        ("ᒂ", "kwa"),
        ("ᒠ", "chwa"),
        ("ᒺ", "mwa"),
        ("ᓏ", "nwa"),
        ("ᔄ", "swa"),
        ("ᔽ", "ywa"),
        ("ᐎ", "wi"),
        ("ᐛ", "wa"),
        ("ᐱ", "pi"),
        ("ᐳ", "pu"),
        ("ᐸ", "pa"),
        ("ᑎ", "ti"),
        ("ᑐ", "tu"),
        ("ᑕ", "ta"),
        ("ᑭ", "ki"),
        ("ᑯ", "ku"),
        ("ᑲ", "ka"),
        ("ᒋ", "chi"),
        ("ᒍ", "chu"),
        ("ᒐ", "cha"),
        ("ᒥ", "mi"),
        ("ᒧ", "mu"),
        ("ᒪ", "ma"),
        ("ᓂ", "ni"),
        ("ᓄ", "nu"),
        ("ᓇ", "na"),
        ("ᓯ", "si"),
        ("ᓱ", "su"),
        ("ᓴ", "sa"),
        ("ᔨ", "yi"),
        ("ᔪ", "yu"),
        ("ᔭ", "ya"),
        ("ᐃ", "i"),
        ("ᐅ", "u"),
        ("ᐊ", "a"),
        ("ᒄ", "kw"),
        ("ᒡ", "ch"),
        ("ᑉ", "p"),
        ("ᑦ", "t"),
        ("ᒃ", "k"),
        ("ᒻ", "m"),
        ("ᓐ", "n"),
        ("ᔅ", "s"),
        ("ᔾ", "y"),
        ("ᐤ", "w"),
        ("ᐧᑲ", "hᑲ"),
        ("᙮", "."),
    ]
    hats = [("aa", "â"), ("ii", "î"), ("uu", "û"), ("oo", "ô")]

    def to_syllabics(self, text):
        syllabics = text.lower()
        for group in [self.hats, self.syllables]:
            for syl, rom in group:
                syllabics = syllabics.replace(rom, syl)
        return syllabics.replace("-", chr(8239)).replace("h", "")
